version: '3'

services:

  app:
    build: .
    image: grid-based-super-resolution-using-spatial-hash-encoding:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
       - ./results:/app/results